version: '3.8'
services:
  background:
    build:
      context: .
      dockerfile: Dockerfile.background
    env_file: 
      - .env
      - /usr/local/.secrets.env
    networks:
      - db_network
      - web_network
    deploy:
      resources:
        limits:
          cpus: "4.0"  # Max 1 CPU core[6][8]
          memory: 2GB  # Max 512MB RAM[6][3]
        reservations:
          cpus: "1.0"   # Guaranteed 0.5 CPU core[6]
          memory: 256M  # Guaranteed 256MB RAM[6]
    
  flask_api:
    container_name: flask_api
    restart: always
    env_file: 
      - .env
      - /usr/local/.secrets.env
    build:
      context: .
      dockerfile: Dockerfile.api
    networks:
      - db_network
      - web_network
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Max 1 CPU core[6][8]
          memory: 1GB  # Max 512MB RAM[6][3]
        reservations:
          cpus: "1.0"   # Guaranteed 0.5 CPU core[6]
          memory: 256M  # Guaranteed 256MB RAM[6]
    
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "3006:3006"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flask_api
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
