version: '3.8'
services:
  flask_api:
    container_name: flask_api
    restart: always
    env_file: 
      - .env
      - /usr/local/.secrets.env
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - /usr/local/.secrets.json:/app/secrets/tokens.json
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "3006:3006"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flask_api
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
