version: '3.8'
services:
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "3006:3006"
    volumes:
      # - ./nginx:/etc/nginx/conf.d
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
