services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BRANDING=${REACT_APP_BRANDING}
    env_file:
      - /root/.secrets/frontend.env
    volumes:
      - frontend_build:/app/build

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html  # Frontend build
      - /root/.secrets/ssl/:/etc/nginx/ssl/   # SSL certificates
    ports:
      - "443:443"
    depends_on:
      - frontend
      # - flask_api

volumes:
  frontend_build:  # Shared volume between frontend and nginx

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge