services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BRANDING=${REACT_APP_BRANDING}
    env_file:
      # - ./api-server-flask/.secrets.env
      - ./.env.secrets
    volumes:
      - frontend_build:/app/build

  background:
    build:
      context: ./api-server-flask
      dockerfile: Dockerfile.background
    env_file: 
      # - ./api-server-flask/.env
      # - ./api-server-flask/.secrets.env
      - ./.env.secrets
    volumes:
      - ./logs:/logs
    networks:
      - db_network
      - web_network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4.0"
    #       memory: 2GB
    #     reservations:
    #       cpus: "1.0"
    #       memory: 256M

  flask_api:
    container_name: flask_api
    restart: always
    env_file: 
      # - ./api-server-flask/.env
      # - ./api-server-flask/.secrets.env
      - ./.env.secrets
    build:
      context: ./api-server-flask
      dockerfile: Dockerfile.api
    volumes:
      - ./logs:/logs
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network

  file_server:
    container_name: file_server
    restart: always
    env_file: 
      # - ./api-server-flask/.env
      - ./.env.secrets
    build:
      context: ./api-server-flask
      dockerfile: Dockerfile.file_server
    volumes:
      - ./logs:/logs
      - ./files:/app/storage
    ports:
      - "5006:5006"
    networks:
      - web_network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html  # Frontend build
      - /root/.secrets/ssl/:/etc/nginx/ssl/   # SSL certificates
    ports:
      - "443:443"
    depends_on:
      - frontend
      - flask_api
      - file_server
      - grafana
    networks:
      - web_network
  
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env.secrets
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_network
    
  
  usdt-api:
    restart: always
    build: 
      context: ./tether_on_eth
    ports:
      - "3100:3100"
    env_file:
      # - ./api-server-flask/.secrets.env
      - ./.env.secrets
    networks:
      - web_network

  metrics:
    container_name: metrics_service
    restart: always
    build:
      context: ./metrics-service
    env_file:
      - ./.env.secrets
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=searchable
      - DB_USER=postgres
      - METRICS_DOMAIN=http://metrics:5007
    ports:
      - "5007:5007"
    depends_on:
      - db
    networks:
      - db_network
      - web_network

  grafana:
    container_name: grafana_service
    image: grafana/grafana:latest
    restart: always
    env_file:
      - ./.env.secrets
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_HTTP_PORT=3000
      - GRAFANA_DB_PASSWORD=${GRAFANA_DB_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    depends_on:
      - db
      - metrics
    networks:
      - db_network
      - web_network

volumes:
  frontend_build:  # Shared volume between frontend and nginx
  postgres_data:
  grafana_data:  # Grafana data persistence
  # file_storage:  # Volume for file storage
  
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge