#!/bin/bash
# Fail2ban setup script

echo "Setting up Fail2ban for Searchable platform..."

# Detect OS
if [ -f /etc/debian_version ]; then
    # Debian/Ubuntu
    sudo apt-get update
    sudo apt-get install -y fail2ban
elif [ -f /etc/redhat-release ]; then
    # RHEL/CentOS/Fedora
    sudo yum install -y epel-release
    sudo yum install -y fail2ban
else
    echo "Unsupported OS. Please install fail2ban manually."
    exit 1
fi

# Create directories
sudo mkdir -p /etc/fail2ban/filter.d

# Copy base configuration
sudo cp jail.conf /etc/fail2ban/jail.conf

# Copy local overrides if needed
if [ -f jail.local ]; then
    sudo cp jail.local /etc/fail2ban/
fi

# Copy filter configurations
sudo cp filter.d/*.conf /etc/fail2ban/filter.d/

# Get the actual log directory from user
echo ""
echo "Please enter the path to your nginx logs directory:"
echo "(Default for production: /home/searchable/searchable/logs/nginx)"
echo "(For Docker: ./logs/nginx or wherever you mount them)"
read -p "Log directory path: " LOG_DIR

if [ -z "$LOG_DIR" ]; then
    LOG_DIR="/home/searchable/searchable/logs/nginx"
fi

# Create log directory if not exists
mkdir -p "$LOG_DIR"

# Create jail.local with correct paths if not exists
if [ ! -f /etc/fail2ban/jail.local ]; then
    cat > /tmp/jail.local <<EOF
# Local environment overrides
# Generated by setup.sh

[nginx-http-auth]
logpath = $LOG_DIR/error.log

[nginx-noscript]
logpath = $LOG_DIR/access.log

[nginx-badbots]
logpath = $LOG_DIR/access.log

[nginx-noproxy]
logpath = $LOG_DIR/access.log

[nginx-req-limit]
logpath = $LOG_DIR/error.log

[searchable-api]
logpath = $LOG_DIR/access.log

[searchable-auth]
logpath = ${LOG_DIR%/nginx}/flask_api.log
EOF
    sudo mv /tmp/jail.local /etc/fail2ban/jail.local
fi

# Enable and restart fail2ban
sudo systemctl enable fail2ban
sudo systemctl restart fail2ban

# Check status
sudo fail2ban-client status

echo ""
echo "Fail2ban setup complete!"
echo ""
echo "Configuration:"
echo "  Main config: /etc/fail2ban/jail.conf"
echo "  Local overrides: /etc/fail2ban/jail.local"
echo "  Log directory: $LOG_DIR"
echo ""
echo "Useful commands:"
echo "  sudo fail2ban-client status                          # Show all jails"
echo "  sudo fail2ban-client status searchable-api           # Show specific jail"
echo "  sudo fail2ban-client set searchable-api unbanip <IP> # Unban IP"
echo "  sudo tail -f /var/log/fail2ban.log                  # Monitor fail2ban log"
echo ""
echo "To test fail2ban is working:"
echo "  1. Try multiple failed logins to trigger searchable-auth"
echo "  2. Check banned IPs: sudo fail2ban-client status searchable-auth"